from typing import Iterable, List, Tuple
import torch
import torch_geometric
from torch_geometric.nn.models import Node2Vec
from torchmetrics import AUROC, AveragePrecision
from models import RandomGaussian
from math import ceil
from data.hypergraph import Hypergraph
from itertools import chain

def train_predict_node2vec(node2vec_model: Node2Vec, batch_size: int = 512, num_workers: int = 0, device="cpu") -> torch.Tensor:
    """
    Trains Node2Vec model and returns node feature matrix.
    
    :param node2vec_model: Node2Vec model to be trained.
    :type node2vec_model: Node2Vec
    :param batch_size: Batch size.
    :type batch_size: int
    :param num_workers: Number of workers for dataloading.
    :type num_workers: int
    :param device: Device where training will be performed. (default: "cpu")
    :return: Node feature matrix of shape (num_nodes, num_features).
    :rtype: Tensor
    """
    device = torch.device(device)
    node2vec_model.to(device)
    optimizer = torch.optim.Adam(list(node2vec_model.parameters()), lr=0.01)

    loader = node2vec_model.loader(batch_size=batch_size, shuffle=True, num_workers=num_workers)
    node2vec_model.train()
    for pos_rw, neg_rw in loader:
        optimizer.zero_grad()
        loss = node2vec_model.loss(pos_rw.to(device), neg_rw.to(device))
        loss.backward()
        optimizer.step()
    node2vec_model.eval()
    with torch.no_grad():
        x = node2vec_model().detach()
    return x

def validate_and_preprocess_graph(graph: torch_geometric.data.Data) -> torch_geometric.data.Data:
    """
    Validates the graph data and preprocesses it. Masks are added if missing,
    labels are reshaped and converted to float if needed.
    
    :param graph: Graph data.
    :type graph: torch_geometric.data.Data
    :return: Initially passed graph with necessary modifications.
    :rtype: torch_geometric.data.Data
    """
    if not isinstance(graph, torch_geometric.data.Data) or graph.x==None or graph.edge_index==None or graph.y==None:
        assert "Graph component must be a torch_geometric.data.Data object with attributes: x, edge_index, and y."
    if len(graph.y.shape)>=2 and graph.y.shape[1]!=1:
        assert "The current function was designed for binary classes only."
    if graph.edge_weight==None:
        graph.edge_weight = torch.ones((graph.edge_index.shape[1],))
    if graph.train_mask==None:
        graph.train_mask = torch.ones((graph.num_nodes,), dtype=torch.bool)
    if graph.val_mask==None:
        graph.val_mask = torch.ones((graph.num_nodes,), dtype=torch.bool)
    graph.y = graph.y.float()
    if len(graph.y.shape)==1:
        graph.y = graph.y.reshape(-1, 1)
    return graph

def train_GNN(model: torch.nn.Module, graph: torch_geometric.data.Data, x: torch.Tensor,
              patience: int = 0, delta: float = 0.0, weight: torch.Tensor = None,
              device="cpu") -> torch.Tensor:
    """
    Trains Graph Neural Network model on the provided graph and returns final predictions.
    During training early stopping technique is used, it stops the training process
    when the validation loss does not improve on more than 'delta' per step for
    'patience' steps in a row. If patience is 0, the training stops immediately
    after the first failure to improve the validation loss by more than 'delta'.
    
    :param model: Graph Neural Network model to be trained.
    :type model: torch.nn.Module
    :param graph: Graph data.
    :type graph: torch_geometric.data.Data
    :param x: Graph node feature matrix of shape (num_nodes, num_features).
    :type x: torch.Tensor
    :param patience: The number of steps for which the absence of improvement
    of the validation loss by more than 'delta' is tolerated before training is stopped. (default: 0)
    :type patience: int
    :param delta: The minimum improvement of the validation loss which is count as significant,
    i.e. the minimum decrease of the loss on the validation set required to reset the patience counter. (default: 0.0)
    :type delta: float
    :param weight: Weight of the positive class utilized in the loss function. Use None to weight all classes equally. (default: None)
    :type weight: torch.Tensor
    :param device: Device where training is performed. (default: "cpu")
    :return: Prediction logits generated by the trained model. Tensor of shape (num_nodes,).
    :rtype: Tensor
    """
    device = torch.device(device)
    model.to(device)
    last_loss = float("inf")
    current_patience = patience
    loss_fn = torch.nn.BCEWithLogitsLoss(weight)
    parameters = model.parameters()
    if isinstance(graph.x, torch.nn.Parameter):
        parameters = chain(parameters, [x])
    optimizer = torch.optim.Adam(parameters, 0.01)

    # verify the data format, fix existing data, and add missing data
    graph = validate_and_preprocess_graph(graph)

    while current_patience>=0:
        # train
        model.train()
        optimizer.zero_grad()
        preds = model(x.to(device), graph.edge_index.to(device), edge_weight=graph.edge_weight.to(device))
        loss = loss_fn(preds[graph.train_mask.to(device)], graph.y.to(device)[graph.train_mask.to(device)])
        loss.backward()
        optimizer.step()
        # evaluate
        model.eval()
        with torch.no_grad():
            loss = loss_fn(preds[graph.val_mask.to(device)], graph.y.to(device)[graph.val_mask.to(device)])
        # early stopping
        if last_loss-loss<delta:
            current_patience-=1
        else:
            current_patience = patience
        last_loss = min(loss.item(), last_loss)
    preds = preds.detach()
    return preds[:, 0]

def train_GNN_batches(model: torch.nn.Module, graph: torch_geometric.data.Data,
                      x: torch.Tensor, num_neighbors: int = 3, patience: int = 0,
                      delta: float = 0.0, batch_size: int = 512, num_workers: int = 0,
                      weight: torch.Tensor = None, device="cpu") -> torch.Tensor:
    """
    Trains Graph Neural Network model on the provided graph and returns final predictions.
    Model is trained in batches using LinkNeighborLoader. This loader first selects
    a sample of edges from the set of input edges and then constructs a subgraph
    from all the nodes present in this list by sampling num_neighbors neighbors in each iteration.
    During training early stopping technique is used, it stops the training process
    when the validation loss does not improve on more than 'delta' per step for
    'patience' steps in a row. If patience is 0, the training stops immediately
    after the first failure to improve the validation loss by more than 'delta'.
    
    :param model: Graph Neural Network model to be trained.
    :type model: torch.nn.Module
    :param graph: Graph data.
    :type graph: torch_geometric.data.Data
    :param x: Graph node feature matrix of shape (num_nodes, num_features).
    :type x: torch.Tensor
    :param num_neighbors: The number of neighbors to sample for each node in batch
    in each iteration. If an entry is set to -1, all neighbors will be included.
    :type num_neighbors: int
    :param patience: The number of steps for which the absence of improvement
    of the validation loss by more than 'delta' is tolerated before training is stopped. (default: 0)
    :type patience: int
    :param delta: The minimum improvement of the validation loss which is count as significant,
    i.e. the minimum decrease of the loss on the validation set required to reset the patience counter. (default: 0.0)
    :type delta: float
    :param batch_size: Batch size of edges subset.
    :type batch_size: int
    :param num_workers: Number of workers for dataloading.
    :type num_workers: int
    :param weight: Weight of the positive class utilized in the loss function. Use None to weight all classes equally. (default: None)
    :type weight: torch.Tensor
    :param device: Device where training is performed. (default: "cpu")
    :return: Prediction logits generated by the trained model. Tensor of shape (num_nodes,).
    :rtype: Tensor
    """
    device = torch.device(device)
    model.to(device)
    last_loss = float("inf")
    current_patience = patience
    loss_fn = torch.nn.BCEWithLogitsLoss(weight)
    parameters = model.parameters()
    if isinstance(x, torch.nn.Parameter):
        parameters = chain(parameters, [x])
    optimizer = torch.optim.Adam(parameters, 0.005)

    # verify the data format, fix existing data, and add missing data
    graph = validate_and_preprocess_graph(graph)
    loader = torch_geometric.loader.LinkNeighborLoader(graph, batch_size=batch_size, num_neighbors=[num_neighbors], shuffle=True, num_workers=num_workers)

    while current_patience>=0:
        model.train()
        # train
        for batch_graph in loader:
            if batch_graph.train_mask.sum()==0:
                continue
            batch_graph = batch_graph.to(device)
            optimizer.zero_grad()
            batch_edge_weight = graph.edge_weight[batch_graph.input_id.to(graph.edge_weight.device)].to(device)
            batch_preds = model(x[batch_graph.n_id.cpu()].to(device), batch_graph.edge_label_index, edge_weight=batch_edge_weight)
            loss = loss_fn(batch_preds[batch_graph.train_mask], batch_graph.y[batch_graph.train_mask])
            loss.backward()
            optimizer.step()
        # evaluate
        model.eval()
        with torch.no_grad():
            loss = torch.tensor(0.0, device=device)
            preds = torch.zeros_like(graph.y, device=device)
            for batch_graph in loader:
                batch_graph = batch_graph.to(device)
                batch_edge_weight = graph.edge_weight[batch_graph.input_id.to(graph.edge_weight.device)].to(device)
                batch_preds = model(x[batch_graph.n_id.cpu()].to(device), batch_graph.edge_label_index, edge_weight=batch_edge_weight)
                if batch_graph.val_mask.sum()!=0:
                    loss += loss_fn(batch_preds[batch_graph.val_mask], batch_graph.y[batch_graph.val_mask])
                preds[batch_graph.n_id] = batch_preds
            loss /= len(loader)
        # early stopping
        if last_loss-loss<delta:
            current_patience-=1
        else:
            current_patience = patience
        last_loss = min(loss.item(), last_loss)
    return preds[:, 0]

def validate_and_preprocess_hypergraph(hypergraph: Hypergraph, x: torch.Tensor) -> Hypergraph:
    """
    Validates the hypergraph data and feature matrix, preprocesses hypergraph data.
    Masks are added if missing, labels are reshaped and converted to float if needed.
    
    :param hypergraph: Hypergraph data.
    :type hypergraph: Hypergraph
    :param x: Feature matrix of shape (num_nodes, num_features).
    :type x: torch.Tensor
    :return: Initially passed hypergraph with necessary modifications.
    :rtype: Hypergraph
    """
    if (not isinstance(hypergraph, Hypergraph)) or x==None or hypergraph.hyperedge_index==None or hypergraph.y==None:
        assert "Hypergraph component must be a data.hypergraph.Hypergraph object with attributes: x, hyperedge_index, and y."
    if hypergraph.hyperedge_weight==None:
        hypergraph.hyperedge_weight = torch.ones((hypergraph.num_edges,))
    if hypergraph.train_mask==None:
        hypergraph.train_mask = torch.ones((hypergraph.num_nodes,), dtype=torch.bool)
    if hypergraph.val_mask==None:
        hypergraph.train_mask = torch.ones((hypergraph.num_nodes,), dtype=torch.bool)
    if len(hypergraph.y.shape)>=2 and hypergraph.y.shape[1]!=1:
        assert "This function was designed for binary classes only."
    if len(hypergraph.y.shape)==1:
        hypergraph.y = hypergraph.y.reshape(-1, 1)
    hypergraph.y = hypergraph.y.float()
    return hypergraph

def train_HGNN(model: torch.nn.Module, hypergraph: Hypergraph, x: torch.Tensor,
               hyperedge_attr: torch.Tensor = None, patience: int = 0,
               delta: float = 0.0, weight=None, device="cpu") -> torch.Tensor:
    """
    Trains Hypergraph Neural Network model on the provided graph and returns final predictions.
    During training early stopping technique is used, it stops the training process
    when the validation loss does not improve on more than 'delta' per step for
    'patience' steps in a row. If patience is 0, the training stops immediately
    after the first failure to improve the validation loss by more than 'delta'.
    
    :param model: Hypergraph Neural Network model to be trained.
    :type model: torch.nn.Module
    :param hypergraph: Hypergraph data.
    :type hypergraph: Hypergraph
    :param x: Hypernode feature matrix of shape (num_nodes, num_features).
    :type x: torch.Tensor
    :param hyperedge_attr: Hyperedge feature matrix of shape (num_edges, num_hyperedge_features).
    None if hyperedge features are not provided. (default: None)
    :type hyperedge_attr: torch.Tensor
    :param patience: The number of steps for which the absence of improvement
    of the validation loss by more than 'delta' is tolerated before training is stopped. (default: 0)
    :type patience: int
    :param delta: The minimum improvement of the validation loss which is count as significant,
    i.e. the minimum decrease of the loss on the validation set required to reset the patience counter. (default: 0.0)
    :type delta: float
    :param weight: Weight of the positive class utilized in the loss function. Use None to weight all classes equally. (default: None)
    :type weight: torch.Tensor
    :param device: Device where training is performed. (default: "cpu")
    :return: Prediction logits generated by the trained model. Tensor of shape (num_nodes,).
    :rtype: Tensor
    """
    device = torch.device(device)
    model.to(device)
    last_loss = float("inf")
    current_patience = patience
    loss_fn = torch.nn.BCEWithLogitsLoss(weight)
    parameters = model.parameters()
    if isinstance(x, torch.nn.Parameter):
        parameters = chain(parameters, [x])
    optimizer = torch.optim.Adam(parameters, 0.01)

    # verify the data format, fix existing data, and add missing data
    hypergraph = validate_and_preprocess_hypergraph(hypergraph, x)
    if hyperedge_attr==None and model.supports_hyperedge_attr:
        hyperedge_attr = RandomGaussian(x.shape[-1])(hypergraph.num_edges)

    while current_patience>=0:
        # train
        model.train()
        optimizer.zero_grad()
        kwargs = {"hyperedge_index": hypergraph.hyperedge_index.to(device)}
        if x is not None:
            kwargs["x"] = x.to(device)
        if model.supports_hyperedge_attr:
            kwargs["hyperedge_attr"] = hyperedge_attr.to(device)
        if model.supports_hyperedge_weight:
            kwargs["hyperedge_weight"] = hypergraph.hyperedge_weight.to(device)
        preds = model(**kwargs)
        loss = loss_fn(preds[hypergraph.train_mask.to(device)], hypergraph.y.to(device)[hypergraph.train_mask.to(device)])
        loss.backward()
        optimizer.step()
        # evaluate
        model.eval()
        with torch.no_grad():
            loss = loss_fn(preds[hypergraph.val_mask.to(device)], hypergraph.y.to(device)[hypergraph.val_mask.to(device)])
        # early stopping
        if last_loss-loss<delta:
            current_patience-=1
        else:
            current_patience = patience
        last_loss = min(loss.item(), last_loss)
    preds = preds.detach()
    return preds[:, 0]

class HGNN_batch_sampler(torch.utils.data.Sampler):
    """
    Batch sampler for training Hypergraph Neural Networks. This is an auxilliary class
    for batch dataloader for hypergraph neural network training. It is an enumerable
    that generates indexes of hyperedges to include in each batch. It also provides
    a collate function for the dataloader which reindexes hypernodes and hyperedges in the batch
    and generates the mask based on the hypernodes and hyperedges in the batch and the
    current mode (train or val). "train" mode is used for training when train_mask
    should be returned by collate function, and "eval" mode is used for validation
    when val_mask is used instead.
    """
    def __init__(self, hypergraph: Hypergraph, sample: str = None, batch_size: int = 64, val: bool = False):
        """
        Initializes the batch sampler.
        
        :param hypergraph: Hypergraph data which connections are sampled by dataloader.
        :type hypergraph: Hypergraph
        :param batch_size: The number of incident connections to sample for each batch,
        i.e. number of pair to sample from hyperedge_index. (default: 64)
        :param sample: Specifies the sampling strategy to use. If None the hypernode-hyperedge
        pairs are sampled in random order. If 'hypernodes' is specified as sampling strategy,
        then hypernode-hyperedge pairs with similar hypernodes will tend to be sampled together.
        If 'hyperedges' is specified as sampling strategy, then hypernode-hyperedge pairs with similar
        hypernodes will tend to be sampled together.
        :type sample: str
        :type batch_size: int
        :param val: Whether the sampler is initialized in validation mode (True) or not (False). (default: False)
        :type val: bool
        """
        self.hypergraph = hypergraph
        self.sample = sample
        self.val = val
        self.batch_size = batch_size
        self.shuffle()
    
    def shuffle(self) -> None:
        """
        Shuffles the connections in the hypergraph (pairs of hyperedge_index).
        It is recommended to be called between any two training epochs.
        """
        if self.sample=="hypernodes":
            order = torch.rand((self.hypergraph.num_nodes,))[self.hypergraph.hyperedge_index[0]]
        elif self.sample=="hyperedges":
            order = torch.rand((self.hypergraph.num_edges,))[self.hypergraph.hyperedge_index[1]]
        else:
            order = torch.rand((self.hypergraph.hyperedge_index.shape[1],))
        self.order = torch.argsort(order, stable=True).tolist()
    
    def collate(self, batch_hyperedge_index: List[torch.Tensor]
                ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Collate function for the dataloader. It reindexes hypernodes and hyperedges in the batch
        and generates the mask based on the hypernodes and hyperedges in the batch and the
        current mode (train or val).
        
        :param batch_hyperedge_index: List of tensors of shape (2,) containing hypernode and hyperedge
        indexes, s.t. hypernode is incident to this hyperedge.
        :type batch_hyperedge_index: List[torch.Tensor]
        :return: Tuple with 4 entries: tensor of shape (N,) containing hypernode
        indexes that are used in this batch, tensor of shape (E,) containing
        hyperedge indexes that are used in this batch, subset of hyperedge_index
        used for the current batch reindexed such that the new index of hypernodes
        and hyperedges would correspond to their corresponding position in
        two previous tensors, mask (train or validation depending on self.val)
        restricted to the values that correspond to the hypernodes from the
        first tensor.
        :rtype: Tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]
        """
        batch_hyperedge_index = torch.stack(batch_hyperedge_index).T
        # reindex hypernodes and hyperedges in the batch
        batch_hypernodes, batch_hyperedge_index[0] = torch.unique(batch_hyperedge_index[0], return_inverse=True)
        batch_hyperedges, batch_hyperedge_index[1] = torch.unique(batch_hyperedge_index[1], return_inverse=True)
        # get the mask for the batch based on the current mode (train or val)
        if self.val:
            batch_mask = self.hypergraph.val_mask[batch_hypernodes]
        else:
            batch_mask = self.hypergraph.train_mask[batch_hypernodes]
        return batch_hypernodes, batch_hyperedges, batch_hyperedge_index, batch_mask

    def __len__(self):
        """
        Returns the number of batches per epoch.
        """
        return ceil(self.hypergraph.hyperedge_index.shape[1]/self.batch_size)
    
    def __iter__(self) -> Iterable[torch.Tensor]:
        """
        Returns an iterable that generates indexes of hyperedge_index to include in each batch.

        :return: Iterable that generates indexes of hyperedge_index to include in each batch.
        :rtype: Iterable[Tensor]
        """
        for i in range(0, self.hypergraph.hyperedge_index.shape[1], self.batch_size):
            yield self.order[i:i+self.batch_size]
    
    def train(self):
        """
        Sets training mode. This would result in train_mask being returned by the "collate" function.
        """
        self.val = False
    
    def eval(self):
        """
        Sets evaluation mode. This would result in val_mask being returned by the "collate" function.
        """
        self.val = True

def train_HGNN_batches(model: torch.nn.Module, hypergraph: Hypergraph, x: torch.Tensor,
                       sample: str = None, batch_size:list = 64, num_workers: int = 0,
                       hyperedge_attr: torch.Tensor = None, patience: int = 0,
                       delta: float = 0.0, weight=None, device="cpu") -> torch.Tensor:
    """
    Trains Hypergraph Neural Network model on the provided hypergraph and returns final predictions.
    Model is trained in batches by sampling a batch from the incident list (list consisting of
    pairs hypernode-hyperedge). Sampling is performed in a way to keep incidence connections
    of the same hypernode in the same batch in most cases.
    During training early stopping technique is used, it stops the training process
    when the validation loss does not improve on more than 'delta' per step for
    'patience' steps in a row. If patience is 0, the training stops immediately
    after the first failure to improve the validation loss by more than 'delta'.
    
    :param model: Hypergraph Neural Network model to be trained.
    :type model: torch.nn.Module
    :param hypergraph: Hypergraph data.
    :type hypergraph: Hypergraph
    :param x: Hypernode feature matrix of shape (num_nodes, num_features).
    :type x: torch.Tensor
    :param sample: Specifies the sampling strategy to use. If None the hypernode-hyperedge
    pairs are sampled in random order. If 'hypernodes' is specified as sampling strategy,
    then hypernode-hyperedge pairs with similar hypernodes will tend to be sampled together.
    If 'hyperedges' is specified as sampling strategy, then hypernode-hyperedge pairs with similar
    hypernodes will tend to be sampled together.
    :type sample: str
    :param batch_size: Batch size of subset of incident list (number of hypernode-hyperedge pairs). (default: 64)
    :type batch_size: list
    :param num_workers: Number of workers for dataloading. 0 stands for using only the main process. (default: 0)
    :type num_workers: int
    :param hyperedge_attr: Hyperedge feature matrix of shape (num_edges, num_hyperedge_features).
    None if hyperedge features are not provided. (default: None)
    :type hyperedge_attr: torch.Tensor
    :param patience: The number of steps for which the absence of improvement
    of the validation loss by more than 'delta' is tolerated before training is stopped. (default: 0)
    :type patience: int
    :param delta: The minimum improvement of the validation loss which is count as significant,
    i.e. the minimum decrease of the loss on the validation set required to reset the patience counter. (default: 0.0)
    :type delta: float
    :param weight: Weight of the positive class utilized in the loss function. Use None to weight all classes equally. (default: None)
    :type weight: torch.Tensor
    :param device: Device where training is performed. (default: "cpu")
    :return: Prediction logits generated by the trained model. Tensor of shape (num_nodes,).
    :rtype: Tensor
    """
    device = torch.device(device)
    model.to(device)
    last_loss = float("inf")
    current_patience = patience
    loss_fn = torch.nn.BCEWithLogitsLoss(weight)
    parameters = model.parameters()
    if isinstance(x, torch.nn.Parameter):
        parameters = chain(parameters, [x])
    optimizer = torch.optim.Adam(parameters, 0.005)

    # verify the data format, fix existing data, and add missing data
    hypergraph = validate_and_preprocess_hypergraph(hypergraph, x)
    if hyperedge_attr==None and model.supports_hyperedge_attr:
        hyperedge_attr = RandomGaussian(x.shape[-1])(hypergraph.num_edges)
    
    # initialize dataloader
    batch_sampler = HGNN_batch_sampler(hypergraph, sample, batch_size)
    dataloader = torch.utils.data.DataLoader(hypergraph.hyperedge_index.T, batch_sampler=batch_sampler, num_workers=num_workers, collate_fn=batch_sampler.collate)
    
    while current_patience>=0:
        # train
        batch_sampler.train()
        model.train()
        for batch_hypernodes, batch_hyperedges, batch_hyperedge_index, batch_train_mask in dataloader:
            if batch_train_mask.sum()==0:
                continue
            optimizer.zero_grad()
            kwargs = {"hyperedge_index": batch_hyperedge_index.to(device)}
            if x is not None:
                kwargs["x"] = x[batch_hypernodes].to(device)
            if model.supports_hyperedge_attr:
                kwargs["hyperedge_attr"] = hyperedge_attr[batch_hyperedges].to(device)
            if model.supports_hyperedge_weight:
                kwargs["hyperedge_weight"] = hypergraph.hyperedge_weight[batch_hyperedges].to(device)
            batch_preds = model(**kwargs)
            loss = loss_fn(batch_preds[batch_train_mask.to(device)], hypergraph.y[batch_hypernodes][batch_train_mask].to(device))
            loss.backward()
            optimizer.step()
        # evaluate
        batch_sampler.eval()
        model.eval()
        with torch.no_grad():
            loss = torch.tensor(0.0, device=device)
            preds = torch.zeros_like(hypergraph.y, device=device)
            for batch_hypernodes, batch_hyperedges, batch_hyperedge_index, batch_val_mask in dataloader:
                kwargs = {}
                if model.supports_hyperedge_attr:
                    kwargs["hyperedge_attr"] = hyperedge_attr[batch_hyperedges].to(device)
                if model.supports_hyperedge_weight:
                    kwargs["hyperedge_weight"] = hypergraph.hyperedge_weight[batch_hyperedges].to(device)
                batch_preds = model(x[batch_hypernodes].to(device), batch_hyperedge_index.to(device), **kwargs)
                if batch_val_mask.sum()!=0:
                    loss += loss_fn(batch_preds[batch_val_mask.to(device)], hypergraph.y[batch_hypernodes][batch_val_mask].to(device))
                preds[batch_hypernodes] = batch_preds
            loss /= ceil(hypergraph.hyperedge_index.shape[1] / batch_size)
        # early stopping
        if last_loss-loss<delta:
            current_patience-=1
        else:
            current_patience = patience
        last_loss = min(loss.item(), last_loss)
        batch_sampler.shuffle()
    preds = preds.detach()
    return preds[:, 0]

def evaluate(preds: torch.Tensor, target: torch.Tensor) -> Tuple[float, float]:
    """
    Evaluates the predictions using ROC AUC and PR AUC (Average Precision) metrics.
    
    :param preds: Prediction float logits generated by the model of shape (num_nodes,).
    :type preds: torch.Tensor
    :param target: Binary float target labels of shape (num_nodes, 1).
    :type target: torch.Tensor
    :return: Tuple containing ROC AUC and PR AUC (Average Precision) scores.
    :rtype: Tuple[float, float]
    """
    roc_auc = AUROC('binary')(preds, target)
    pr_auc = AveragePrecision('binary')(preds, target)
    return roc_auc, pr_auc